language: python
python:
  - "3.6.5"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install codecov
  - pip install -r requirements.txt
script:
  - py.test --cov=app/api app/tests
after_success:
  - codecov --token=54348b92-7393-401c-8d60-f8f8449c1674