language: python
python:
  - "3.6.5"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install codecov
  - pip install -r requirements.txt
env: 
  - export TEST_DATABASE_URL="dbname='test_questioner' host='127.0.0.1' port='5432' user='postgres' password=''"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE questioner;' -U postgres  
script:
  - py.test --cov=app/api app/tests
after_success:
  - codecov --token=54348b92-7393-401c-8d60-f8f8449c1674